@echo off
setlocal

REM === CONFIGURAÇÕES ===
set MYSQL_PATH="C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe"
set MYSQL_USER=root
set MYSQL_PASSWORD=sua_senha_aqui
set DATABASE=covid

REM === IMPORTAR COVID DEATHS ===
echo Importando CovidDeaths.csv...
%MYSQL_PATH% --local-infile=1 -u %MYSQL_USER% -p%MYSQL_PASSWORD% %DATABASE% -e "LOAD DATA LOCAL INFILE 'C:/Users/muril/OneDrive/Documentos/MYSQLAlexAnalyst/Covid/CovidDeaths.csv' INTO TABLE covid_deaths FIELDS TERMINATED BY ';' ENCLOSED BY '\"' LINES TERMINATED BY '\n' IGNORE 1 ROWS (@iso_code, @continent, @location, @date_str, @total_cases, @new_cases, @new_cases_smoothed, @total_deaths, @new_deaths, @new_deaths_smoothed, @total_cases_per_million, @new_cases_per_million, @new_cases_smoothed_per_million, @total_deaths_per_million, @new_deaths_per_million, @new_deaths_smoothed_per_million, @reproduction_rate, @icu_patients, @icu_patients_per_million, @hosp_patients, @hosp_patients_per_million, @weekly_icu_admissions, @weekly_icu_admissions_per_million, @weekly_hosp_admissions, @weekly_hosp_admissions_per_million) SET iso_code = @iso_code, continent = @continent, location = @location, date = STR_TO_DATE(@date_str, '%%d/%%m/%%Y'), total_cases = @total_cases, new_cases = @new_cases, new_cases_smoothed = @new_cases_smoothed, total_deaths = @total_deaths, new_deaths = @new_deaths, new_deaths_smoothed = @new_deaths_smoothed, total_cases_per_million = @total_cases_per_million, new_cases_per_million = @new_cases_per_million, new_cases_smoothed_per_million = @new_cases_smoothed_per_million, total_deaths_per_million = @total_deaths_per_million, new_deaths_per_million = @new_deaths_per_million, new_deaths_smoothed_per_million = @new_deaths_smoothed_per_million, reproduction_rate = @reproduction_rate, icu_patients = @icu_patients, icu_patients_per_million = @icu_patients_per_million, hosp_patients = @hosp_patients, hosp_patients_per_million = @hosp_patients_per_million, weekly_icu_admissions = @weekly_icu_admissions, weekly_icu_admissions_per_million = @weekly_icu_admissions_per_million, weekly_hosp_admissions = @weekly_hosp_admissions, weekly_hosp_admissions_per_million = @weekly_hosp_admissions_per_million;"

REM === IMPORTAR COVID VACCINATIONS ===
echo Importando CovidVaccinations.csv...
%MYSQL_PATH% --local-infile=1 -u %MYSQL_USER% -p%MYSQL_PASSWORD% %DATABASE% -e "LOAD DATA LOCAL INFILE 'C:/Users/muril/OneDrive/Documentos/MYSQLAlexAnalyst/Covid/CovidVaccinations.csv' INTO TABLE covid_vaccinations FIELDS TERMINATED BY ';' ENCLOSED BY '\"' LINES TERMINATED BY '\n' IGNORE 1 ROWS (@iso_code, @continent, @location, @date_str, @new_tests, @total_tests, @total_tests_per_thousand, @new_tests_per_thousand, @new_tests_smoothed, @new_tests_smoothed_per_thousand, @positive_rate, @tests_per_case, @tests_units, @total_vaccinations, @people_vaccinated, @people_fully_vaccinated, @new_vaccinations, @new_vaccinations_smoothed, @total_vaccinations_per_hundred, @people_vaccinated_per_hundred, @people_fully_vaccinated_per_hundred, @new_vaccinations_smoothed_per_million, @stringency_index, @population_density, @median_age, @aged_65_older, @aged_70_older, @gdp_per_capita, @extreme_poverty, @cardiovasc_death_rate, @diabetes_prevalence, @female_smokers, @male_smokers, @handwashing_facilities, @hospital_beds_per_thousand, @life_expectancy, @human_development_index) SET iso_code = @iso_code, continent = @continent, location = @location, date = STR_TO_DATE(@date_str, '%%d/%%m/%%Y'), new_tests = @new_tests, total_tests = @total_tests, total_tests_per_thousand = @total_tests_per_thousand, new_tests_per_thousand = @new_tests_per_thousand, new_tests_smoothed = @new_tests_smoothed, new_tests_smoothed_per_thousand = @new_tests_smoothed_per_thousand, positive_rate = @positive_rate, tests_per_case = @tests_per_case, tests_units = @tests_units, total_vaccinations = @total_vaccinations, people_vaccinated = @people_vaccinated, people_fully_vaccinated = @people_fully_vaccinated, new_vaccinations = @new_vaccinations, new_vaccinations_smoothed = @new_vaccinations_smoothed, total_vaccinations_per_hundred = @total_vaccinations_per_hundred, people_vaccinated_per_hundred = @people_vaccinated_per_hundred, people_fully_vaccinated_per_hundred = @people_fully_vaccinated_per_hundred, new_vaccinations_smoothed_per_million = @new_vaccinations_smoothed_per_million, stringency_index = @stringency_index, population_density = @population_density, median_age = @median_age, aged_65_older = @aged_65_older, aged_70_older = @aged_70_older, gdp_per_capita = @gdp_per_capita, extreme_poverty = @extreme_poverty, cardiovasc_death_rate = @cardiovasc_death_rate, diabetes_prevalence = @diabetes_prevalence, female_smokers = @female_smokers, male_smokers = @male_smokers, handwashing_facilities = @handwashing_facilities, hospital_beds_per_thousand = @hospital_beds_per_thousand, life_expectancy = @life_expectancy, human_development_index = @human_development_index;"

echo Importações concluídas.
pause
endlocal
